mc_gethost: Use unsigned char instead of u_char
Fix build on musl
error: unknown type name 'u_char'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Acked-by: Cyril Hrubis <chrubis@suse.cz>